language: c

sudo: true

matrix:
  include:
    - env: BUILD=stack STACK_YAML=stack.yaml

addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
    - libc6:i386

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_install:
 # update machine and install mlton
 - sudo apt-get -qq update
 - sudo apt-get install -y mlton
 # install Haskell stack 
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis-setup.sh
 # install smackage
 - git clone git://github.com/standardml/smackage
 - cd smackage
 - make mlton
 - bin/smackage refresh
 - export PATH=$HOME/.smackage/bin:$PATH
 - bin/smackage get smackage
 - bin/smackage make smackage mlton
 - bin/smackage make smackage install
 - cd ..
 - rm -rf $HOME/smackage
 - mkdir -p $HOME/.mlton
 - echo "SMACKAGE $HOME/.smackage/lib" > $HOME/.mlton/mlb-path-map
 - echo "aplparse git git://github.com/melsman/aplparse.git" >> $HOME/.smackage/sources.local
 - echo "kitlib git git://github.com/melsman/kitlib.git" >> $HOME/.smackage/sources.local
 - echo "apltail git git://github.com/melsman/apltail.git" >> $HOME/.smackage/sources.local
 - smackage refresh
 - smackage get apltail
 - export MLCOMP="mlton -mlb-path-map $HOME/.mlton/mlb-path-map"
 - smackage make apltail aplt-mlton
 - smackage make apltail install
 - export APLT_ROOT=$(pwd)/.smackage/lib/apltail/v1
 - export APLT=aplt
 # install Futhark
 - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
 - tar xf futhark-nightly-linux-x86_64.tar.xz
 - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)

install:
 - stack --no-terminal test --only-dependencies -j 3

script:
 - stack --no-terminal test --haddock --no-haddock-deps -j 3
 - stack install
