language: c

sudo: false

matrix:
  include:
    - env: BUILD=stack STACK_YAML=stack.yaml

addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
    - libc6:i386

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_install:
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis-setup.sh
 - git clone https://github.com/melsman/apltail.git
 # Something nasty happens now.
 - export APLT_ROOT=$(pwd)/apltail
 - wget http://napoleon.hiperfit.dk/~athas/aplt -O $APLT_ROOT/aplt
 - chmod +x $APLT_ROOT/aplt
 # Nastyness over; now it's all good.
 - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
 - tar xf futhark-nightly-linux-x86_64.tar.xz
 - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)

install:
 - stack --no-terminal test --only-dependencies -j 3

script:
 - stack --no-terminal test --haddock --no-haddock-deps -j 3
 - stack install
